# Generated by Django 5.2.4 on 2025-07-30 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '공지사항 카테고리',
                'verbose_name_plural': '공지사항 카테고리',
            },
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='게시판명')),
                ('url', models.URLField(verbose_name='게시판 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='notices.noticecategory')),
            ],
            options={
                'verbose_name': '공지사항 게시판',
                'verbose_name_plural': '공지사항 게시판',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='제목')),
                ('url', models.URLField(verbose_name='공지사항 URL')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='작성자')),
                ('published_date', models.DateField(verbose_name='게시일')),
                ('view_count', models.IntegerField(blank=True, default=0, null=True, verbose_name='조회수')),
                ('is_important', models.BooleanField(default=False, verbose_name='중요공지')),
                ('crawled_at', models.DateTimeField(auto_now_add=True, verbose_name='크롤링 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='notices.noticeboard')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항',
                'ordering': ['-published_date', '-crawled_at'],
                'unique_together': {('board', 'url')},
            },
        ),
    ]
