# Generated by Django 5.2.4 on 2025-07-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-published_date', 'display_order', '-crawled_at'], 'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
        migrations.AddField(
            model_name='notice',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='표시 순서'),
        ),
    ]
