# Generated by Django 5.2.4 on 2025-07-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_notice_options_notice_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='noticeboard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='noticecategory',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='notice',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='noticeboard',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='noticecategory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='noticecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='crawled_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notice',
            name='published_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notice',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='noticeboard',
            name='url',
            field=models.URLField(),
        ),
        migrations.RemoveField(
            model_name='notice',
            name='updated_at',
        ),
    ]
