name: Periodic Crawling

on:
  schedule:
    # 매시간 0분에 실행 (UTC 기준)
    - cron: '0 * * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  crawl:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger crawling
      run: |
        curl -X POST "${{ secrets.RENDER_APP_URL }}/api/manual-crawl/" \
          -H "Authorization: Bearer ${{ secrets.CRAWL_AUTH_TOKEN }}" \
          -H "Content-Type: application/json"
